AppWeb/Controllers/ListadoMateriasController.cs
using AppWeb.filtro;
using AppWeb.Models;
using AppWeb.Models.Datos;
using AppWeb.Models.Modelos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AppWeb.Controllers
{
    //[Autorizacion_rol(modulo: "Usuarios", Autorizacion_rol.Roles.admin)]
    public class ListadoMateriasController : Controller
    {
       
        public ActionResult Index()
        {
            
            return View();
        }
        
        public ActionResult Nuevo(RegistroMaterias modelo)
        {
            using (ColegioEntities db = new ColegioEntities())
            {
                if (string.IsNullOrEmpty(modelo.Materias.Nombre_Materia))
                {
                    TempData["Message"] = "Debe ingresar un nombre para la materia";
                    return RedirectToAction("Index");
                }
                // Verificar si ya existe un usuario con el mismo nombre
                if (db.Materias.Any(u => u.Nombre_Materia == modelo.Materias.Nombre_Materia))
                {
                    TempData["Message"] = "El nombre de la materia ya existe.";
                    return RedirectToAction("Index");
                }
                else
                {
                    Materias modeloV = new Materias()
                    {
                        Nombre_Materia = modelo.Materias.Nombre_Materia,

                    };
                    new materias().Guardar(modeloV);


                    return RedirectToAction("Index", "Materias");
                }
            }
            // Si la validación falla, volver a cargar la vista con los errores
            
            return RedirectToAction("Index", modelo);
        }
        
        public ActionResult Editar(int id)
        {
            using (ColegioEntities db = new ColegioEntities())
            {
                var materias = db.Materias.Find(id);

                if (materias == null)
                {
                    return HttpNotFound();
                }

                var modelo = new EditarMaterias
                {
                    Materias = materias,
                };

                return View(modelo);
            }
        }
        [HttpPost]
        public ActionResult Editar(EditarMaterias modelo)
        {
            using (ColegioEntities db = new ColegioEntities())
            {
                if (string.IsNullOrEmpty(modelo.Materias.Nombre_Materia))
                {
                    TempData["Message"] = "Debe ingresar un nombre para la materia";
                    return RedirectToAction("Index");
                }
                // Verificar si ya existe un curso con el mismo nombre
                if (db.Materias.Any(u => u.Nombre_Materia == modelo.Materias.Nombre_Materia && u.Id_Materia != modelo.Materias.Id_Materia))
                {
                    TempData["Message"] = "El nombre de la materia ya existe.";
                    return RedirectToAction("Index");
                }
                else
                {
                    Materias materias = db.Materias.Find(modelo.Materias.Id_Materia);
                    materias.Nombre_Materia = modelo.Materias.Nombre_Materia;
                    db.SaveChanges();
                    return RedirectToAction("Index", "Materias");
                }
            }
        }

        public ActionResult Eliminar(int id)
        {
            using (ColegioEntities db = new ColegioEntities())
            {
                var materias = db.Materias.Find(id);

                if (materias == null)
                {
                    return HttpNotFound();
                }

                db.Materias.Remove(materias);
                db.SaveChanges();

                return RedirectToAction("Index", "Materias");
            }
        }

    }


}

AppWeb/Views/ListadoMaterias/Editar.cshtml
@model AppWeb.Models.Modelos.EditarMaterias
@{
    ViewBag.Title = "EditarMaterias";
}

<h2>Editar Materia</h2>

@using (Html.BeginForm("Editar", "ListadoMaterias", FormMethod.Post, new { id = "formulario-editar" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Materias.Id_Materia)

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Materias.Nombre_Materia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Materias.Nombre_Materia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Materias.Nombre_Materia, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (TempData["Message"] != null)
        {
            <div class="alert alert-danger" role="alert">
                @Html.Raw(TempData["Message"])
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(document).ready(function () {
        $('#formulario-editar').submit(function (event) {
            event.preventDefault(); // prevenir el envío del formulario por defecto
            $.ajax({
                url: $(this).attr('action'), // obtener la URL del controlador que manejará el envío del formulario
                type: $(this).attr('method'), // obtener el método HTTP (POST, GET, PUT, DELETE, etc.) utilizado para enviar el formulario
                data: $(this).serialize(), // serializar el formulario para enviarlo como datos
                success: function (response) {
                    if (response.success) { // si la edición se realizó correctamente
                        location.reload(); // recargar la página para mostrar los cambios actualizados
                    } else {
                        // si se produjo algún error durante la edición, mostrar un mensaje de error en la página
                        $('#alerta-error').text(response.message);
                        $('#alerta-error').show();
                    }
                },
                error: function (xhr, status, error) {
                    // si se produjo un error de comunicación con el servidor, mostrar un mensaje de error en la página
                    $('#alerta-error').text('Error al comunicarse con el servidor.');
                    $('#alerta-error').show();
                }
            });
        });
    });
</script>

AppWeb/Views/ListadoMaterias/Index.cshtml
@model AppWeb.Models.Modelos.RegistroMaterias
@{
    ViewBag.Title = "Index";
}

<h2>Agregar Materia</h2>

@using (Html.BeginForm("Nuevo", "ListadoMaterias", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Materias.Nombre_Materia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Materias.Nombre_Materia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Materias.Nombre_Materia, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (TempData["Message"] != null)
        {
            <div class="alert alert-danger" role="alert">
                @TempData["Message"]
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}