AppWeb/Controllers/ListadoDocentesController.cs
using AppWeb.filtro;
using AppWeb.Models;
using AppWeb.Models.Datos;
using AppWeb.Models.Modelos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AppWeb.Controllers
{
    //[Autorizacion_rol(modulo: "Usuarios", Autorizacion_rol.Roles.admin)]
    public class ListadoDocentesController : Controller
    {
        private IEnumerable<SelectListItem> usuarios;
        // GET: ListadoUsuarios
        public ActionResult Index()
        {
            agregar();
            RegistroDocente modelo = new RegistroDocente()
            {
                ListadoUsuarios = usuarios
            };
            return View(modelo);
        }
        public ActionResult agregar()
        {
            usuarios = new usuarios().Consultar().ToList().Select(
             p => new SelectListItem { Value = p.Id_Usuario.ToString(), Text = p.Nombre_Usuario });
            return View();
        }
        public ActionResult Nuevo(RegistroDocente modelo)
        {
            using (ColegioEntities db = new ColegioEntities())
            {
                if (string.IsNullOrEmpty(modelo.Docentes.Primer_Nombre) ||
                   string.IsNullOrEmpty(modelo.Docentes.Primer_Apellido))
                {
                    TempData["Message"] = "Los campos Primer Nombre, Primer Apellido e Identificación son requeridos.";
                    return RedirectToAction("Index");
                }
                // Verificar si ya existe un usuario con el mismo nombre

                Docentes modeloV = new Docentes()
                    {
                        Primer_Nombre = modelo.Docentes.Primer_Nombre,
                        Segundo_Nombre = modelo.Docentes.Segundo_Nombre,
                        Primer_Apellido = modelo.Docentes.Primer_Apellido,
                        Segundo_Apellido = modelo.Docentes.Segundo_Apellido,
                        Identificacion = modelo.Docentes.Identificacion,
                        Id_Usuario = modelo.Docentes.Id_Usuario
                    };
                    new docentes().Guardar(modeloV);
                    agregar();
                    modelo = new RegistroDocente()
                    {
                        ListadoUsuarios = usuarios
                    };
                    return RedirectToAction("Index", "Docentes");
                
            }
            // Si la validación falla, volver a cargar la vista con los errores
            modelo.ListadoUsuarios = usuarios;
            return RedirectToAction("Index", modelo);
        }
        
        public ActionResult Editar(int id)
        {
            using (ColegioEntities db = new ColegioEntities())
            {
                var docente = db.Docentes.Find(id);

                if (docente == null)
                {
                    return HttpNotFound();
                }

                var modelo = new EditarDocente
                {
                    Docentes = docente,
                    ListadoUsuarios = db.Usuarios.Select(r => new SelectListItem
                    {
                        Value = r.Id_Usuario.ToString(),
                        Text = r.Nombre_Usuario
                    }).ToList()
                };

                return View(modelo);
            }
        }
        [HttpPost]
        public ActionResult Editar(EditarDocente modelo)
        {
            using (ColegioEntities db = new ColegioEntities())
            {
                // Verificar si ya existe un usuario con el mismo nombre

                Docentes docentes = db.Docentes.Find(modelo.Docentes.Id_Docente);
                docentes.Primer_Nombre = modelo.Docentes.Primer_Nombre;
                docentes.Segundo_Nombre = modelo.Docentes.Segundo_Nombre;
                docentes.Primer_Apellido = modelo.Docentes.Primer_Apellido;
                docentes.Segundo_Apellido = modelo.Docentes.Segundo_Apellido;
                docentes.Identificacion = modelo.Docentes.Identificacion;
                docentes.Id_Usuario = modelo.Docentes.Id_Usuario;
                db.SaveChanges();
                return RedirectToAction("Index", "Docentes");

            }
        }

        public ActionResult Eliminar(int id)
        {
            using (ColegioEntities db = new ColegioEntities())
            {
                var docentes = db.Docentes.Find(id);

                if (docentes == null)
                {
                    return HttpNotFound();
                }

                db.Docentes.Remove(docentes);
                db.SaveChanges();

                return RedirectToAction("Index", "Docentes");
            }
        }

    }


}

AppWeb/Views/ListadoDocentes/Editar.cshtml
@model AppWeb.Models.Modelos.EditarDocente
@{
    ViewBag.Title = "EditarDocente";
}

<h2>Editar Docentes</h2>

@using (Html.BeginForm("Editar", "ListadoDocentes", FormMethod.Post, new { id = "formulario-editar" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Docentes.Id_Docente)
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Primer_Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Primer_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Primer_Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Segundo_Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Segundo_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Segundo_Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Primer_Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Primer_Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Primer_Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Segundo_Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Segundo_Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Segundo_Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Identificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Identificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Identificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Id_Usuario, "Nombre Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Docentes.Id_Usuario, Model.ListadoUsuarios)
                @Html.ValidationMessageFor(model => model.Docentes.Id_Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (TempData["Message"] != null)
        {
            <div class="alert alert-danger" role="alert">
                @Html.Raw(TempData["Message"])
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(document).ready(function () {
        $('#formulario-editar').submit(function (event) {
            event.preventDefault(); // prevenir el envío del formulario por defecto
            $.ajax({
                url: $(this).attr('action'), // obtener la URL del controlador que manejará el envío del formulario
                type: $(this).attr('method'), // obtener el método HTTP (POST, GET, PUT, DELETE, etc.) utilizado para enviar el formulario
                data: $(this).serialize(), // serializar el formulario para enviarlo como datos
                success: function (response) {
                    if (response.success) { // si la edición se realizó correctamente
                        location.reload(); // recargar la página para mostrar los cambios actualizados
                    } else {
                        // si se produjo algún error durante la edición, mostrar un mensaje de error en la página
                        $('#alerta-error').text(response.message);
                        $('#alerta-error').show();
                    }
                },
                error: function (xhr, status, error) {
                    // si se produjo un error de comunicación con el servidor, mostrar un mensaje de error en la página
                    $('#alerta-error').text('Error al comunicarse con el servidor.');
                    $('#alerta-error').show();
                }
            });
        });
    });
</script>

AppWeb/Views/ListadoDocentes/Index.cshtml
@model AppWeb.Models.Modelos.RegistroDocente
@{
    ViewBag.Title = "Index";
}

<h2>Agregar Docente</h2>

@using (Html.BeginForm("Nuevo", "ListadoDocentes", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Primer_Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Primer_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Primer_Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Segundo_Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Segundo_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Segundo_Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Primer_Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Primer_Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Primer_Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Segundo_Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Segundo_Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Segundo_Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Identificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Docentes.Identificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Docentes.Identificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.Docentes.Id_Usuario, "Nombre Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Docentes.Id_Usuario, Model.ListadoUsuarios)
                @Html.ValidationMessageFor(model => model.Docentes.Id_Usuario, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-danger" role="alert">
                @TempData["Message"]
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}